# sgndracula is a custom theme made followning the palette at https://draculatheme.com/contribute
theme = "sgndracula"
# This is from the web app
client_id = "65b708073fc0480ea92a077233ca87bd"
app_refresh_duration_in_ms = 100
playback_refresh_duration_in_ms = 1000
cover_image_refresh_duration_in_ms = 2000
track_table_item_max_len = 32
enable_media_control = true
default_device = "spotify-player"
play_icon = "⏸"
pause_icon = "▶"
cover_img_length = 9
cover_img_width = 5
playback_window_width = 6

[device]
name = "hornet"
device_type = "computer"
volume = 65
bitrate = 160
audio_cache = true
