[[keymaps]]
command = "PreviousTrack"
key_sequence = "N"
[[keymaps]]
command = "Repeat"
key_sequence = "r"
[[keymaps]]
command = "Shuffle"
key_sequence = "s"
[[keymaps]]
command = "VolumeUp"
key_sequence = "="
[[keymaps]]
command = "SeekForward"
key_sequence = "right"
[[keymaps]]
command = "SeekBackward"
key_sequence = "left"
[[keymaps]]
command = "FocusNextWindow"
key_sequence = "l"
[[keymaps]]
command = "FocusPreviousWindow"
key_sequence = "h"
[[keymaps]]
command = "RefreshPlayback"
key_sequence = "C-r p"
[[keymaps]]
command = "RestartIntegratedClient"
key_sequence = "C-r c"
[[keymaps]]
command = "SwitchTheme"
key_sequence = "t"
[[keymaps]]
command = "SwitchDevice"
key_sequence = "d"
[[keymaps]]
command = "LyricPage"
key_sequence = "C-l"
[[keymaps]]
command = "LyricPage"
key_sequence = ": l enter"
[[keymaps]]
command = "Quit"
key_sequence = ": q enter"
