# Edited dracula theme following https://spec.draculatheme.com/
[[themes]]
name = "sgndracula"
[themes.palette]
background = "#282a36"
foreground = "#f8f8f2"
black = "#21222c"
blue = "#bd93f9"
cyan = "#8be9fd"
green = "#50fa7b"
magenta = "#ff79c6"
red = "#ff5555"
white = "#f8f8f2"
yellow = "#ffb86c"
bright_black = "#6272a4"
bright_blue = "#d6acff"
bright_cyan = "#a4ffff"
bright_green = "#69ff94"
bright_magenta = "#ff92df"
bright_red = "#ff6e6e"
bright_white = "#ffffff"
bright_yellow = "#f1fa8c"
selection_background = "#44475a"
selection_foreground =  "#69ff94"

# The `component_style` field of a theme is optional.
# If not specified, a default value will be used as below:
[themes.component_style]
block_title = { fg = "Blue"  }
playback_track = { fg = "Yellow", modifiers = ["Bold"] }
playback_album = { fg = "Cyan" }
playback_metadata = { fg = "BrightBlack" }
playback_progress_bar = { bg = "SelectionBackground", fg = "Green" }
current_playing = { fg = "Green", modifiers = ["Bold"] }
page_desc = { fg = "Yellow", modifiers = ["Bold"] }
table_header = { fg = "BrightBlack" }
